[package]
name = "casegraph-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
casegraph-application = { path = "../casegraph-application" }
casegraph-domain = { path = "../casegraph-domain" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true

